cask_args appdir: '/Applications'

tap 'homebrew/bundle'
tap 'caskroom/fonts'

brew 'bash'
brew 'bash-completion2'
brew 'git'
brew 'go'
brew 'hub'
brew 'node'
brew 'openssl'
brew 'ripgrep'
brew 'wget'

cask '1password'
cask 'sublime-text'
cask 'google-chrome'
cask 'firefox'
# cask 'slack'
cask 'vlc'
cask 'font-source-code-pro'
